[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200